steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull gcr.io/$PROJECT_ID/my_app:latest || exit 0

  # Build the application image
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build \
        --cache-from gcr.io/$PROJECT_ID/my_app:latest \
        -t gcr.io/$PROJECT_ID/my_app:latest \
        . && docker push gcr.io/$PROJECT_ID/my_app:latest

  # Deploy to cloud run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$PROJECT_ID",
        "--image",
        "gcr.io/$PROJECT_ID/my_app:latest",
        "--region",
        "australia-southeast1",
        "--platform",
        "managed",
      ]

  # Switch traffic over to new version
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "services",
        "update-traffic",
        "$PROJECT_ID",
        "--to-latest",
        "--region",
        "australia-southeast1",
        "--platform",
        "managed",
      ]

timeout: 800s
images:
  - "gcr.io/$PROJECT_ID/my_app:latest"
